### ISSUE TITLE
Storage labs

### ISSUE THREAD

**Issue by cmeralto** [cmeralto/SEBC#2]
Distcp stucked at Map phase on 100%

17/06/06 13:35:27 INFO tools.DistCp: DistCp job-id: job_1496749990034_0003
17/06/06 13:35:27 INFO mapreduce.Job: Running job: job_1496749990034_0003
17/06/06 13:35:33 INFO mapreduce.Job: Job job_1496749990034_0003 running in uber mode : false
17/06/06 13:35:33 INFO mapreduce.Job:  map 0% reduce 0%
17/06/06 13:35:39 INFO mapreduce.Job:  map 33% reduce 0%
17/06/06 13:35:45 INFO mapreduce.Job:  map 67% reduce 0%
17/06/06 13:35:46 INFO mapreduce.Job:  map 100% reduce 0%

**Comment by cmeralto** [comment]
2017-06-06 13:51:31,398 WARN [main] org.apache.hadoop.hdfs.DFSClient: Failed to connect to /**172.31.46.176**:50010 for block, add to deadNodes and continue. java.net.NoRouteToHostException: No route to host

RM logs shows that can't resolve the internal IP. Since the public IPs changes when the machines goes down... We will use the distcp on our own clusters (intra cluster)

**Comment by cmeralto** [comment]
sudo -u hdfs hadoop distcp hdfs://ec2-52-31-120-57.eu-west-1.compute.amazonaws.com:8020/cmeralto/teragenout hdfs://ec2-52-31-120-57.eu-west-1.compute.amazonaws.com:8020/fpcel

Distcp command issued on the same cluster

**Comment by cmeralto** [comment]
Same error when trying replicate a folder using BDR:

Started At 	June 6, 2017 1:14 PM
Duration 	a few seconds
Command Details 	View
Diagnostics 	Collect Diagnostic Data
MapReduce Job 	
HDFS Replication Report 	Download Listing CSV Download Status CSV
Message 	HDFS replication command failed.

Setup Error: 	
java.net.NoRouteToHostException: No Route to Host from ip-172-31-36-205.eu-west-1.compute.internal/172.31.36.205 to ip-172-31-34-16.eu-west-1.compute.internal:8020 failed on socket timeout exception: java.net.NoRouteToHostException: No route to host; For more details see: http://wiki.apache.org/hadoop/NoRouteToHost
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)

**Comment by cmeralto** [comment]
Issue on enabling HDFS HA (Error) due to wrong permission on Journal Nodes folders. After the correct assignation (chown hdfs:hadoop /data/01/jn) Cloudera Manager wizard stuck on abort step.
Solution:
- HDFS service -> Disable HDFS HA
- HDFS service -> Enable HDFS HA

**Comment by cmeralto** [comment]
http://ec2-52-30-123-172.eu-west-1.compute.amazonaws.com:7180

Storage Lab Completed!
